  <h2>Customer review</h2>
    <div class="title">
        <span class="widget-title"><?php echo __("Customer Name : "); ?></span>
        <span class="widget-title-val"><?php echo $block->getData('customer1'); ?></span>
    </div>
  <div class="place">
      <span class="widget-title"><?php echo __("Place : "); ?></span>
      <span><?php echo $block->getData('woplace'); ?></span>
  </div>
  <div class="txt1">
      <span class="widget-title"><?php echo __("Text1 : "); ?></span>
      <span class="widget-title-val"><?php echo $block->getData('wotext1'); ?></span>
  </div>
  <div class="txt2">
      <span class="widget-title"><?php echo __("Text2 : "); ?></span>
      <span><?php echo $block->getData('wotext2'); ?></span>
  </div>
    <div class="description">
        <span class="widget-desc"><?php echo __("Product Description : "); ?></span>
        <span class="widget-desc-val"><?php echo $block->getData('wodescription'); ?></span>
    </div>
    <div class="image">
        <span class="widget-desc"><?php echo __("Product Image media: "); ?></span>
        <span class="widget-pimage"> <?php echo $block->getData('wop_image'); ?> </span>
</span>
    </div>
    <div class="cimage">
        <span class="widget-desc"><?php echo __("customer Image : "); ?></span>
        <span class="widget-cu_image"><?php echo $csimage=$block->getData('woc_image');?><br>
    </div>
<!--                                2nd slide                           -->
  <h2>Customer review</h2>
  <div class="title">
      <span class="widget-title"><?php echo __("Customer Name : "); ?></span>
      <span><?php echo $block->getData('customer2'); ?></span>
  </div>
  <div class="place">
      <span class="widget-title"><?php echo __("Place : "); ?></span>
      <span><?php echo $block->getData('wtplace'); ?></span>
  </div>
  <div class="txt1">
      <span class="widget-title"><?php echo __("Text1 : "); ?></span>
      <span ><?php echo $block->getData('wttext1'); ?></span>
  </div>
  <div class="txt2">
      <span class="widget-title"><?php echo __("Text2 : "); ?></span>
      <span><?php echo $block->getData('wttext2'); ?></span>
  </div>
  <div class="description">
      <span class="widget-desc"><?php echo __("Product Description : "); ?></span>
      <span ><?php echo $block->getData('wtdescription'); ?></span>
  </div>
  <div class="image">
      <span class="widget-desc"><?php echo __("Product Image "); ?></span>
      <span > <?php echo $block->getData('wtp_image'); ?> </span>
      </span>
  </div>
  <div class="cimage">
      <span class="widget-desc"><?php echo __("customer Image : "); ?></span>
      <span ><?php echo $csimage=$block->getData('wtc_image');?><br>

  </div>
  <!--                                3rd slide                           -->
  <h2>Customer review</h2>
  <div class="title">
      <span class="widget-title"><?php echo __("Customer Name : "); ?></span>
      <span><?php echo $block->getData('customer3'); ?></span>
  </div>
  <div class="place">
      <span class="widget-title"><?php echo __("Place : "); ?></span>
      <span><?php echo $block->getData('wthplace'); ?></span>
  </div>
  <div class="txt1">
      <span class="widget-title"><?php echo __("Text1 : "); ?></span>
      <span ><?php echo $block->getData('wthtext1'); ?></span>
  </div>
  <div class="txt2">
      <span class="widget-title"><?php echo __("Text2 : "); ?></span>
      <span><?php echo $block->getData('wthtext2'); ?></span>
  </div>
  <div class="description">
      <span class="widget-desc"><?php echo __("Product Description : "); ?></span>
      <span ><?php echo $block->getData('wthdescription'); ?></span>
  </div>
  <div class="image">
      <span class="widget-desc"><?php echo __("Product Image "); ?></span>
      <span > <?php echo $block->getData('wthp_image'); ?> </span>
      </span>
  </div>
  <div class="cimage">
      <span class="widget-desc"><?php echo __("customer Image : "); ?></span>
      <span ><?php echo $csimage=$block->getData('wthc_image');?><br>

  </div>
  <!--                                4th slide                           -->
  <h2>Customer review</h2>
  <div class="title">
      <span class="widget-title"><?php echo __("Customer Name : "); ?></span>
      <span><?php echo $block->getData('customer4'); ?></span>
  </div>
  <div class="place">
      <span class="widget-title"><?php echo __("Place : "); ?></span>
      <span><?php echo $block->getData('wfoplace'); ?></span>
  </div>
  <div class="txt1">
      <span class="widget-title"><?php echo __("Text1 : "); ?></span>
      <span ><?php echo $block->getData('wfotext1'); ?></span>
  </div>
  <div class="txt2">
      <span class="widget-title"><?php echo __("Text2 : "); ?></span>
      <span><?php echo $block->getData('wfotext2'); ?></span>
  </div>
  <div class="description">
      <span class="widget-desc"><?php echo __("Product Description : "); ?></span>
      <span ><?php echo $block->getData('wfodescription'); ?></span>
  </div>
  <div class="image">
      <span class="widget-desc"><?php echo __("Product Image "); ?></span>
      <span > <?php echo $block->getData('wfop_image'); ?> </span>
      </span>
  </div>
  <div class="cimage">
      <span class="widget-desc"><?php echo __("customer Image : "); ?></span>
      <span ><?php echo $csimage=$block->getData('wfoc_image');?><br>
  </div>

  <!--                               5th Slide                     -->
  <h2>Customer review</h2>
  <div class="title">
      <span class="widget-title"><?php echo __("Customer Name : "); ?></span>
      <span><?php echo $block->getData('customer5'); ?></span>
  </div>
  <div class="place">
      <span class="widget-title"><?php echo __("Place : "); ?></span>
      <span><?php echo $block->getData('wfvplace'); ?></span>
  </div>
  <div class="txt1">
      <span class="widget-title"><?php echo __("Text1 : "); ?></span>
      <span ><?php echo $block->getData('wfvtext1'); ?></span>
  </div>
  <div class="txt2">
      <span class="widget-title"><?php echo __("Text2 : "); ?></span>
      <span><?php echo $block->getData('wfvtext2'); ?></span>
  </div>
  <div class="description">
      <span class="widget-desc"><?php echo __("Product Description : "); ?></span>
      <span ><?php echo $block->getData('wfvdescription'); ?></span>
  </div>
  <div class="image">
      <span class="widget-desc"><?php echo __("Product Image "); ?></span>
      <span > <?php echo $block->getData('wfvp_image'); ?> </span>
      </span>
  </div>
  <div class="cimage">
      <span class="widget-desc"><?php echo __("customer Image : "); ?></span>
      <span ><?php echo $csimage=$block->getData('wfvc_image');?><br>

  </div>


