<script>
    require([
        'jquery',
        'prototype',
    ], function (jQuery) {
        jQuery('#token').click(function () {
            // Set isAjax to true and append form_key in the request.
            params = {
                form_key: '<?php echo $block->getFormKey() ?>',
                isAjax: true
            };
            // Make the ajax call and handel data.
            jQuery.ajax({
                showLoader: true,
                url: "<?php echo $block->getAjaxUrl() ?>",
                data: params,
                dataType: 'json'
            }).done(function (data) {
                alert(data);
                console.log(data);
            });
        });
    });
</script>

<?php echo $block->getButtonHtml() ?>
