<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<h3 class="share-design">share this design</h3>
<span class="copy-link">Copy Link</span>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()) :?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product::class)->getEmailToFriendUrl($_product)) ?>"
       class="action mailto friend"><span><?= $block->escapeHtml(__('Mail')) ?></span></a>
<?php endif; ?>
