<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpZipCodeValidator
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<span style="padding-left:250px;">
    <a  href="<?= $block->escapeUrl(
        $block->getViewFileUrl('Webkul_MpZipCodeValidator::zipcodes.csv')
    );?>"><?= $block->escapeHtml(__("Download Example CSV")); ?>
    </a>
</span>
<div class="region_note" style="padding-top: 10px; padding-left: 20px; font-weight: bolder;">
    <?= $block->escapeHtml(
        __('Note:- Zipcodes containing only Alphabets, Numerals, Space, UnderScore and Hyphen are allowed.')
    ); ?>
</div>
<script>
    require([
        'jquery',
        'mage/adminhtml/grid',
        'prototype'
    ], function(jQuery){
        jQuery("#edit_form").append('<input type="hidden" id="product_ids" name="product_ids" value="">');
        jQuery("#edit_form").append('<input type="hidden" name="old_product_ids" value="<?= $block->escapeHtml(
            $block->getSelectedProductIds()
        ); ?>">');
        jQuery(document).ready(function(){
            jQuery(document).on('click', 'table tbody tr td', function(event) {
                setValues();
            });
        });
        function setValues() {
            var ids = [];
            jQuery("table tbody tr td input:checkbox").each(function(){
                if(jQuery(this).prop("checked")) {
                    id = jQuery(this).val();
                    ids.push(id);
                }
            });
            jQuery("#product_ids").val(ids);
        }
    });
</script>