<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
/**
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<a
    class="logo"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?>
            <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?>
    />
</a>
<!-- <a class="sticky-logo" href="<?= $block->escapeUrl($block->getUrl('')) ?>">
	<img src='<?php echo $this->getViewFileUrl('images/sticky_Store_logo-03.png'); ?>' alt="sticky logo" width="180" />
</a> -->
<script type="text/javascript">
    require(['jquery'],function ($) {
        $("body").addClass("loading");
        if($('ul.header.links').find('.customer-register-link').length <= 0) {
            $("body").addClass("logged-in");
        } else {
            $("body").addClass("logged-out");
        }
        $(window).load(function (){
            console.log('windowloaded');
            var selectcity = $('div#switcher-store').clone();
            if($('ul.header.links').find('.customer-register-link').length <= 0) {
                $("body").addClass("logged-in");
                $("body").removeClass("logged-out");
            } else {
                $("body").addClass("logged-out");
                $("body").removeClass("logged-in");
            }
            if ($(window).width() > 767) {
                if($('ul.header.links').find('.customer-register-link').length <= 0) {
                } else {
                    $(".minicart-wrapper + ul.header.links").prepend(selectcity);
                }
            }
            $("body").removeClass("loading");
        });
    });
</script>