<?php
$formdata=$block->getFormData();
if(!empty($formdata)):

$code=$formdata['code'];
$email = $formdata['email'];
?>
<h1 class="page-title">
    <span class="base">Reset Your Password</span>
</h1>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <!-- <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend> -->
                <div class="field user-email-id">
                    <span><?= $block->escapeHtml(__('Email Address')) ?></span><span class="user-id"><?= $email ?></span>
                </div>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <!-- <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email:')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div> -->
                        <div class="field name required">
                            <label for="password"
                                   class="label"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                            <div class="control">
                                <input type="password" name="password" id="password"
                                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                       class="input-text"
                                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                       data-validate="{required:true, 'validate-customer-password':true}"
                                       autocomplete="off">
                                <div id="password-strength-meter-container" data-role="password-strength-meter"
                                     aria-live="polite">
                                    <div id="password-strength-meter" class="password-strength-meter">
                                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                                        <span id="password-strength-meter-label"
                                              data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="field confirmation required">
                            <label for="password-confirmation"
                                   class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                            <div class="control">
                                <input type="password" name="password_confirmation"
                                       title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                                       id="password-confirmation"
                                       class="input-text" data-validate="{required:true, equalTo:'#password'}"
                                       autocomplete="off">
                            </div>
                        </div>

                            <div class="control">
                                <input type="hidden" name="code"
                                      id="code" value="<?= $code ?>"
                                       class="input-text" 
                                       autocomplete="off">
                            </div>
                             <div class="control">
                                <input type="hidden" name="email"
                                      id="email" value="<?= $email ?>"
                                       class="input-text" 
                                       autocomplete="off">
                            </div>

                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>


<?php endif; ?>