<?php
$blockObj = $block->getCustomer();
$currenturl =$block->getCurrentUrl(); //http://homelane.local/customer/account
$baseurl = $block->getBaseUrl();      //http://homelane.local/
foreach ($blockObj as $item)
{
    $name = $item['customerName'];
    $email = $item['customerEmail'];
}

?>
<div class="user-profile">
    <div>
        <a class="name"><?= $name ?></a>
        <a class="mail"><?= $email ?></a>
    </div>
</div>
<ul class="account-links">
<?php if($currenturl == $baseurl."customer/account/") {?> 
        <li class="login-profile active"><a href="<?= $this->getUrl('customer/account') ?>">My Profile</a></li>
        <?php }else{?>
    <li class="login-profile"><a href="<?= $this->getUrl('customer/account') ?>">My Profile</a></li>
    <?php }
      if($currenturl ==$baseurl."wishlist/") {?> 
        <li class="login-wishlist active"><a href="<?= $this->getUrl('wishlist') ?>">My Wishlist</a></li>
        <?php }else {?>
        <li class="login-wishlist"><a href="<?= $this->getUrl('wishlist') ?>">My Wishlist</a></li>
        <?php } 
        if($currenturl == $baseurl."") { ?>
            <li class="login-hl active"><a href="<?= $this->getUrl('') ?>">Homelane Care</a></li>
            <?php }else{?>
                <li class="login-hl"><a href="<?= $this->getUrl('') ?>">Homelane Care</a></li>
                <?php } ?>
</ul>
