<?php
$blockObj = $block->getCustomer();
foreach ($blockObj as $item)
{
    $name = $item['customerName'];
    $email = $item['customerEmail'];
}

?>
<div class="user-profile">
    <div>
        <a class="name"><?= $name ?></a>
        <a class="mail"><?= $email ?></a>
    </div>
</div>
<ul class="account-links">
    <li class="login-profile"><a href="<?= $this->getUrl('customer/account') ?>">My Profile</a></li>
    <li class="login-wishlist"><a href="<?= $this->getUrl('wishlist') ?>">My Wishlist</a></li>
    <li class="login-hl"><a href="<?= $this->getUrl('') ?>">Homelane Care</a></li>
</ul>
