<?php
    $isExpanded = $block->isExpanded();
    $attributes = new \Magento\Framework\DataObject();
    $tabs = $block->prepareTabsData();
    if (!$tabs) {
        return;
    }
?>
<div class="product info detailed">
    <div class="product data items <?= $block->getTabsLayout() ?>"
         data-mage-init='{"Swissup_Easytabs/js/tabs": <?= $block->getInitOptions() ?>}'
         id="swissup-easy-tabs"
         data-content-type="Easytabs"
    >
        <?php foreach ($tabs as $_index => $_tab) : ?>
            <?php
                $alias = $_tab['alias'];
                $label = $_tab['title'];
                $attributes->setData([
                    'class' => $isExpanded ? 'title' : 'data switch',
                    'id' => "tab-label-{$alias}-title",
                    'data-toggle' => 'switch',
                ]);
                if ($_tab['is_ajax']) {
                    $attributes->setData(
                        'data-ajaxurl',
                        $block->getAjaxUrl($alias)
                    );
                }
            ?>
            <div class="data item title <?= $isExpanded ? 'active' : '' ?>"
                aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                data-role="collapsible"
                role="tab"
                id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
            <?php if ($isExpanded): ?>
                <h2 <?= $attributes->serialize() ?>><?= /* @escapeNotVerified */ $label ?></h2>
            <?php else: ?>
                <a <?= $attributes->serialize() ?>
                    tabindex="-1"
                    href="#<?= $alias ?>">
                    <?= /* @escapeNotVerified */ $label ?>
                </a>
            <?php endif ?>
            </div>
            <div class="data item content content-prof-description" id="<?= /* @escapeNotVerified */ $alias; ?>" data-role="content">
                <div class="description-content show-more-height">
                    <?= /* @escapeNotVerified */ $_tab['is_ajax'] ? '' : $_tab['child_html'] ?>
                </div>    
                <div class="show-more">
                   
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script>
    require(['jquery','jquery/ui'], function ($) {
        $(document).ready(function() {
            $( ".product.data").find('.data').each(function() {
                var heightContainer = $(this).find('.description-content').height();                
                if(heightContainer > 180){
                    $(this).find('.description-content').parent('.content').addClass('more-content-block');
                }
            });

            $(".show-more").click(function () {
                $(this).parent('.content-prof-description').find('.description-content').toggleClass("show-more-height");
            });
        });
    });
</script>


<script type="text/javascript">
require(['jquery'], function($) {
    $(document).ready(function(){
        if ($(window).width() > 768) {
            $(function() { 
                var sidebarheight = $('.product.media').height();
                if (!!$('.product.media').length) { // make sure "#sticky" element exists
                    var el = $('.product.media');
                    var stickyTop = $('.product.media').offset().top - 55; // returns number
                    var footerTop = $('.block.related').offset().top; // returns number
                    var stickyHeight = $('.product.media').height();
                    $(window).scroll(function(){ // scroll event
                        var windowTop = $(window).scrollTop(); // returns number
                        if ($(this).scrollTop() > 1) {
                            el.addClass('sticky');
                            let stickyHeader = $('.product.media .fotorama__stage').height();
                            el.css({height: stickyHeader});
                        } else {
                            el.removeClass('sticky');
                        }
                    });
                }
            });
        };  
    });
});
</script>
