<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */
$welcomeMessage = $block->getWelcome();
?>
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $escaper->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <?php /* <span class="not-logged-in"
              data-bind="html: '<?= $escaper->escapeHtmlAttr($welcomeMessage) ?>'"></span> 
         <?= $block->getBlockHtml('header.additional') ?> */?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
<script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/modal'],function ($,modal) {
        function openloginmodal() {
                if ($('body').hasClass('logged-out')) {
                console.log('customer loged Out');
                $('.action.towishlist').removeAttr("data-post");
                $('.action.towishlist').removeAttr("data-action");
                $('.action.towishlist').on('click', function(e){
                    e.preventDefault();
                    $('#customer-popup-login').modal('openModal');
                });
                $(document).on('click', '.logged-out .action.mailto.friend', function (e) {
                    e.preventDefault();
                    $('#customer-popup-login').modal('openModal');
                });
                } else {
                    console.log('customer loged In');
                }
            }
        $(document).ready(function() {
            $("li.link.wishlist").click(function(e) {
                e.preventDefault();
                $('#customer-popup-login').modal('openModal');
            });
            openloginmodal();
            $("body").bind("ajaxComplete", function(e, xhr, settings){
                //console.log('ajax loaded...');
                openloginmodal();
            });
        });
    });
</script>
