<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */
 
/**
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php 
    $smsProfileHelper = $this->helper('Magedelight\SMSProfile\Helper\Data');
    $required = 0;
    $validate = $smsProfileHelper->getSmsProfileMailPhoneValidationClass();
    if ($smsProfileHelper->getModuleStatus()) {
        $required = 1;
    }
?>
<form class="form password forget md-forget-password"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <?php if(!$required) { ?>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <?php } else { ?>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address or telephone below to receive a password reset link.')) ?></div>
        <?php } ?>    
        <div class="field email required">
            <?php if(!$required) { ?>
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
             <?php } else { ?> 
                  <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email or Telephone')) ?></span></label>  
             <?php }  ?>
            <div class="control">
                <input <?php if(!$required) { echo 'type="email"';} else { echo 'type="text"'; } ?> name="email" alt="email" id="email_address" class="input-text <?php if($required) { echo $validate;} ?>" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{},"validation":{}}' data-validate="{required:true,  <?php if(!$required) { echo '\'validate-email\':true'; }?>}">
            </div>
            
            <?php if($required) { ?>
                <?php if($smsProfileHelper->getPhoneNote()) { ?>
                <div class="profile-notice-phone">
                    <span><?php echo $smsProfileHelper->getPhoneNote(); ?></span>
                </div> 
                <?php } ?>
                <div class="field">
                    <button class="send_otp_password action primary" style="display: none;margin-top: 15px;" type="button"><?php echo __('Generate OTP');?></button>
                    <span class="otp_generatenote">&nbsp;</span>
                </div>                 
                <?php 
                $sendOtpUrl = $this->getUrl('smsprofile/otp/send');
                $verifyOtpUrl = $this->getUrl('smsprofile/otp/verify');
                echo "<input type='hidden' class='sendUrlforget' value='".$sendOtpUrl."'/>";
                echo "<input type='hidden' class='verifyUrlforget' value='".$verifyOtpUrl."'/>";
                echo "<input type='hidden' class='forgetOtpValidation' name = 'forgetOtpValidation' value='0'/>";
                ?>

                <div class="md_reset_password" style="display: none;">
                   
                     <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                        <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password" id="password"
                                   data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                   data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                   data-validate="{required:true, 'validate-customer-password':true}"
                                   autocomplete="off">
                            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                <div id="password-strength-meter" class="password-strength-meter">
                                    <?= $block->escapeHtml(__('Password Strength')) ?>:
                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                        <?= $block->escapeHtml(__('No Password')) ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field confirmation required">
                        <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                        </div>
                    </div>
                </div>
            <?php }?>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>    
</form>

