<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name"
                       id="name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone"
                       id="telephone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                       class="input-text"
                       type="number" maxlength = "10"
                       oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);"
                       data-validate="{required:true}"
                       onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))"
                       />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                          id="comment"
                          title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"
                ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>

<script>
require(['jquery'], function($) {
    $(document).ready(function() {
        if ($("form#contact-form input[type='text']").val().length > 3) {
            $("form#contact-form input[type='text").parent().addClass('input-has-value');
        } else {
            $("form#contact-form input[type='text").parent().removeClass('input-has-value');
        }
        var inputvalues = $("form#contact-form input#email").val();    
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;    
        if(regex.test(inputvalues)) {
            $("form#contact-form input#email").parent().addClass('input-has-value');
        } else {
            $("form#contact-form input#email").parent().removeClass('input-has-value');
        }
        $('form#contact-form button').prop('disabled', true);
        $("form#contact-form input[type='text']").on('change keyup', function() {
          if ($(this).val().length > 3) {
            $(this).parent().addClass('input-has-value');
          } else {
            $(this).parent().removeClass('input-has-value');
          }  
        });
        $("form#contact-form input#email").on('change keyup',function () {    
            var inputvalues = $(this).val();    
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;    
            if(regex.test(inputvalues)) {    
                $(this).parent().addClass('input-has-value');
            } else {
                $(this).parent().removeClass('input-has-value');
            }
        });
        $("form#contact-form input#telephone").on('change keyup',function () {
            var mobNum = $(this).val();
            if(mobNum.length == 10) {
                $(this).parent().addClass('input-has-value');
            } else {
                $(this).parent().removeClass('input-has-value');
            }
        });
        $("form#contact-form textarea").on('change keyup',function () {
            $(this).parent().find('div.mage-error').hide(); 
            var mobNum = $(this).val();   
            if(mobNum.length > 6) {
                $(this).parent().addClass('input-has-value');
            } else {
                $(this).parent().removeClass('input-has-value');
            }
        });
        $("form#contact-form  .control input, form#contact-form textarea#comment").on('change keyup',function () {
            if ($('.control.input-has-value').length == 4) {
                $('form#contact-form button').prop('disabled', false);
            } else {
                $('form#contact-form button').prop('disabled', true);
            }
        });
    });
});
</script>
