<div class="social-container"> 
    <div class="social-icons">
        <p>share</p>
        <div class="media-content">
            <a class="facebook" href="#"
            data-mage-init='{"popupWindow": {"windowURL":"<?php echo $this->getUrl('https://www.facebook.com/sharer/sharer.php?u=')?>","windowName":"orderitems","width":500,"height":400,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
            ></a>

        </div>
        <div class="media-content">
            <a class="twitter" 
            href="#"
            data-mage-init='{"popupWindow": {"windowURL":"<?php echo $this->getUrl('http://twitter.com/home/?status=')?>","windowName":"orderitems","width":500,"height":400,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
            >
            </a>
        </div>
        <div class="media-content">
            <a class="instagram" 
            href="#"
            data-mage-init='{"popupWindow": {"windowURL":"<?php echo $this->getUrl('https://www.instagram.com/?url=')?>","windowName":"orderitems","width":500,"height":400,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
            ></a>
        </div>
        <div class="media-content">
            <a class="whats-app" 
            href="#"
            data-action="share/whatsapp/share"
            data-mage-init='{"popupWindow": {"windowURL":"<?php echo $this->getUrl('https://wa.me/whatsappphonenumber/?text=')?>","windowName":"orderitems","width":500,"height":400,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
            ></a>
        </div>
    </div>
</div>

<div class="mobile-share">
    <div class="media-content-share">
            <a class="share" href="#"></a>
    </div>
</div>