<?php
use Magento\Cms\Block\BlockByIdentifier;
use Codilar\Store\ViewModel\Overlay;

/** @var BlockByIdentifier $block */
/** @var $viewModel Overlay */
$viewModel = $block->getData("viewModel");
$storeDetails = $viewModel->getStoreDetail();
$mediaUrl = $viewModel->getMediaUrl();
$parsedUrl = $viewModel->getParsedUrl();
$redirect = $viewModel->getHttpResponse();
$baseUrl = $viewModel->getBaseUrl();
foreach ($parsedUrl as $url)
{
    $schema = $url['scheme'];
    $path = $url['path'];
}
$sessionData = $viewModel->getSessionValue();
$cookieData = $viewModel->getWebsiteCookie(); // set cookie and session if website code is present then don't show popup
if ($cookieData == null) {
    if ($sessionData == null) {
?>
<div class="call-popup" data-mage-init='{"callPopup":{}}'>
    <div class="block-title">
        <h3 class="title">
            <span><?php echo __('Please select your city') ?></span>
        </h3>
    </div>
    <?php
    foreach ($storeDetails as $key => $value) {
    $imageUrl = $mediaUrl. 'website/icons/' . $value['imageUrl'];
    $storeName = $value['storeName'];
    $webUrl = $value['webUrl'];
    $parsedWebCode = $viewModel->getParsedWebCode($webUrl);
        foreach ($parsedWebCode as $webCode) {
            $code = $webCode['path'];
    ?>
    <div class="box-store-content">
        <?php if ($imageUrl): ?>
            <div class="store-image">
                <img src="<?php echo $imageUrl ?>" alt="<?php echo $storeName ?>" title="<?php echo $storeName ?>" class="img-responsive" width="200" height="200"/>
            </div>
        <?php endif ?>
        <?php if($storeName): ?>
            <div class="store-name">

                <a target="_blank" onclick="<?php $viewModel->setSessionValue($code); $viewModel->setWebsiteCookie($code); ?>" href="<?php echo $webUrl ?>">
                    <?php echo $storeName ?>
                </a>
            </div>
        <?php endif ?>
    </div>
        <?php } ?>
    <?php } ?>
</div>
    <?php } ?>
<?php } else {
    $viewModel->setSessionValue($cookieData);
    return $redirect->setRedirect($baseUrl.$cookieData);
}
?>
