<?php
use Codilar\Store\ViewModel\Overlay;
use Magento\Cms\Block\BlockByIdentifier;

/** @var BlockByIdentifier $block */
/** @var $viewModel Overlay */
$viewModel = $block->getData("viewModel");
$storeDetails = $viewModel->getStoreDetail();
$websiteName = $viewModel->getWebsite()->getName();
$mediaUrl = $viewModel->getMediaUrl();
$parsedUrl = $viewModel->getParsedUrl();
$redirect = $viewModel->getHttpResponse();
$baseUrl = $viewModel->getBaseUrl();
$currentUrl = $viewModel->getCurrentUrl();
$gets = parse_url($currentUrl);
$queryParam = '?city_change=true';
if (isset($gets['query'])) {
    if (strpos($gets['query'], 'city_change=true') !== false) {
        $queryParam = '';
    } else {
        $queryParam = '&city_change=true';
    }
}
?>
<div class="call-popup" data-mage-init='{"callPopup":{}}'>
    <div class="call-popup-top">
        <div class="call-popup-img">
            <img src='<?php echo $this->getViewFileUrl('images/city-popup-image.png'); ?>' alt="city popup image">
        </div>
        <div class="search-section">
            <h2><?php echo __('Hi There! looking for new furniture?') ?></h2>
            <div class="control">
                <input id="city-search"
                       type="text"
                       name=""
                       value=""
                       placeholder="<?php echo __('Search your city here') ?>"
                       class="input-text"
                       maxlength="" onkeyup="citySearchFunction()" />
            </div>
        </div>
    </div>
    <div class="block-title">
        <h3 class="title">
            <span><?php echo __('Please select your city') ?></span>
        </h3>
    </div>
    <div class="box-store-content">
        <ul id="searchable-content">
        <?php
        foreach ($storeDetails as $key => $value) {
            $imageUrl = $mediaUrl . 'website/icons/' . $value['imageUrl'];
            $highlightedImageUrl = $mediaUrl . 'website/icons/' . $value['highlightedImageUrl'];
            $storeName = $value['storeName'];
            $webUrl = $value['webUrl'];
            $parsedWebCode = $viewModel->getParsedWebCode($webUrl); ?>
            <?php
            if ($websiteName == $storeName) {
                echo '<li class="current-website">';
            } else {
                echo '<li>';
            }
            foreach ($parsedWebCode as $webCode) {
                $code = $webCode['path']; ?>
                <a href="<?php echo $webUrl . '' . $parsedUrl . '' . $queryParam; ?>">
                <?php
                    if ($websiteName == $storeName) {
                        if ($highlightedImageUrl): ?>
                            <div class="store-image">
                                <img src="<?php echo $highlightedImageUrl ?>" alt="<?php echo $storeName ?>" title="<?php echo $storeName ?>" class="img-responsive" width="200" height="200"/>
                            </div>
                        <?php endif ?>
                    <?php } else {?>
                        <?php if ($imageUrl): ?>
                            <div class="store-image">
                                <img src="<?php echo $imageUrl ?>" alt="<?php echo $storeName ?>" title="<?php echo $storeName ?>" class="img-responsive" width="200" height="200"/>
                            </div>
                        <?php endif ?>
                    <?php } ?>
                <?php if ($storeName): ?>
                    <div class="store-name">
                            <?php echo $storeName ?>
                    </div>
                <?php endif ?>
                </a>
            <?php
            } ?>
            </li>
        <?php
        } ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    function citySearchFunction() {
        var input, filter, ul, li, a, i, txtValue;
        input = document.getElementById("city-search");
        filter = input.value.toUpperCase();
        ul = document.getElementById("searchable-content");
        li = ul.getElementsByTagName("li");
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("a")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
</script>
