<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseUrl = $store->getBaseUrl();
$baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);

?>
<form class="query-form" action="<?= $block->getPostUrl() ?>" method="$_POST">
    <h2> Got questions? We’re happy to help out.</h2>
    <fieldset>
            <div class="field required">
                <div class="control">
                    <input name="name" value="" placeholder="ExampleName Here" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('ExampleName Here') ?>" data-validate="{required:true, 'validate-name':true}">
                </div>
            </div>
            <div class="field required">
                <div class="control">
                    <input name="email" value="" placeholder="example@mail.com" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('example@mail.com') ?>" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <div class="field required">
                <div class="control">
                    <input name="phoneno" value="" placeholder="Mobile Number" type="number" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-telephone':true}">
                </div>
            </div>
            <div class="field required">
                <div class="control">
                    <input name="pincode" value="" placeholder="PIN Code" type="number" class="input-text" title="<?php /* @escapeNotVerified */ echo __('PIN Code') ?>" data-validate="{required:true, 'validate-number':true}">
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action login primary" name="send" id="send2-login">
                        <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                    </button>
                </div>
                <p>By submitting this form, you agree to the <a href="<?php /* @escapeNotVerified */ echo $baseUrl.'privacy-policy' ?>"><?php echo __('Privacy Policy'); ?></a> and <a href="<?php /* @escapeNotVerified */ echo $baseUrl.'terms' ?>"><?php echo __('Terms & Conditions'); ?></a></p>
            </div>
    </fieldset>
</form>




