<form class="query-form" data-mage-init='{"validation": {}}'>
    <h2> Got questions? We’re happy to help out.</h2>
    <fieldset>
            <div class="field required">
                <div class="control">
                    <input name="name" id='name' value="" placeholder="Enter your name" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your name') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field required">
                <div class="control">
                    <input name="email" id='email' value="" placeholder="Enter your email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your email') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field required">
                <div class="control phoneno">
                    <input name="phoneno" id='phoneno' value="" placeholder=" Enter your mobile number" type="numer" maxlength="10" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your mobile number') ?>" data-validate="{required:true}" onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))">
                </div>
            </div>
        <div class="field required">
            <div class="control">
                <input name="whatsapp" value="No" type="hidden" checked>
                <input name="whatsapp" id="whatsapp" value="Yes"   type="checkbox" class="input-text checkbox" title="<?php /* @escapeNotVerified */ echo __('You can reach me on WhatsApp') ?>">
                <label for="whatsapp" class="label whatsapp-lable">
                    You can reach me on Whatsapp
                </label>
            </div>
        </div>
            <div class="field required">
                <div class="control pincode">
                    <input name="pincode" id="pincode" value="" placeholder="Enter your residence pincode" type="numer" maxlength="6" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your residence pincode') ?>" data-validate="{required:true}" onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))">
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action login primary" name="send" id="submit-query">
                        <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                    </button>
                </div>
                <p>By submitting this form, you agree to the <a href="<?= $this->getUrl('privacy-policy') ?>"><?php echo __('Privacy Policy'); ?></a> and <a href="<?= $this->getUrl('terms') ?>"><?php echo __('Terms & Conditions'); ?></a></p>
            </div>
    </fieldset>
</form>
        <div id="query-popup" >
        <h2>Thanks for sharing your details. Our team will reach out to you shortly!</h2>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                modalClass: 'query-form-success',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: 'Ok',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#query-popup'));
            $('#submit-query').on('click',function (event) {
                event.preventDefault();
                var name = $("#name").val();
                var emailID = $('#email').val();
                var phoneno = $('#phoneno').val();
                var  whatsapp = $('#whatsapp').val();
                var pincode = $('#pincode').val();
                jQuery.ajax({
                    
                    url: "<?php echo $block->getBaseUrl().'query/query/save'?>",
                    // url: "getAjaxUrl()",
                    data: {name: name,phoneno: phoneno, email: emailID, whatsapp: whatsapp, pincode: pincode},
                    type: "POST",
                    dataType: "json",
                    success: function() {
                               $('#submit-popup').modal('openModal');
                    
                    }
                });
                $("#query-popup").modal("openModal");

            });

        }
    );
</script>
