<form class="query-form" action="<?= $block->getPostUrl() ?>" data-mage-init='{"validation": {}}'  method="$_POST">
    <h2> Got questions? We’re happy to help out.</h2>
    <fieldset>
            <div class="field required">
                <div class="control">
                    <input name="name" value="" placeholder="Enter your name" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your name') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field required">
                <div class="control">
                    <input name="email" value="" placeholder="Enter your email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your email') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="field required">
                <div class="control phoneno">
                    <input name="phoneno" value="" placeholder=" Enter your mobile number" type="number" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your mobile number') ?>" data-validate="{required:true}">
                </div>
            </div>
        <div class="field required">
            <div class="control">
                <input name="whatsapp" value="No" type="hidden" checked>
                <input name="whatsapp" id="whatsapp" value="Yes"   type="checkbox" class="input-text checkbox" title="<?php /* @escapeNotVerified */ echo __('You can reach me on WhatsApp') ?>">
                <label for="whatsapp" class="label whatsapp-lable">
                    You can reach me on Whatsapp
                </label>
            </div>
        </div>
            <div class="field required">
                <div class="control pincode">
                    <input name="pincode" value="" placeholder="Enter your residence pincode" type="number" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Enter your residence pincode') ?>" data-validate="{required:true}">
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action login primary" name="send" id="send2-login">
                        <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                    </button>
                </div>
                <p>By submitting this form, you agree to the <a href="<?= $this->getUrl('privacy-policy') ?>"><?php echo __('Privacy Policy'); ?></a> and <a href="<?= $this->getUrl('terms') ?>"><?php echo __('Terms & Conditions'); ?></a></p>
            </div>
    </fieldset>
</form>




