<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category  Magedelight
 * @package   Magedelight_SMSProfile
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    Magedelight <info@magedelight.com>
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"></div>
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <div class="control">
                    <label class="label"><span>Name</span></label>
                    <input value="<?= $block->escapeHtml($block->getName()) ?>" disabled/>
                </div>
                <div class="control">
                    <label class="label"><span>Phone Number</span></label>
                    <input value="<?= $block->escapeHtml($block->getCustomerMobile()) ?>" disabled/>
                </div>
                <div class="control">
                    <label class="label"><span>Email</span></label>
                    <input value="<?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>" disabled/>
                </div>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
        </div>
    </div>
</div>
