<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpZipCodeValidator
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$allRegions = $block->getAllRegions();
$type = $block->getProductType();
if ($type != 'virtual' && $type != 'downloadable') {
    ?>
<div class="field" id="wk-mp-zcv-region">
    <div><label class="wk-zcv-label"><?= $block->escapeHtml(__("Available Regions")); ?>:</label></div>
    <div>
        <select multiple class="wk-zcv-multiple-select" name="product[available_region][]">
            <?php if (count($allRegions)) {
                foreach ($allRegions as $key => $value) { ?>
                <option value="<?= $block->escapeHtml($value->getId()); ?>">
                    <?= $block->escapeHtml($value->getRegionName()); ?>
                </option>
                <?php } } ?>
        </select>
    </div>
</div>
<?php } ?>
<script type="text/javascript">
        require([
            "jquery",
            "mage/mage"
        ], function($){
            var html = $('#wk-mp-zcv-region');
            $('#wk_mpassignproduct_form .fieldset [class="field"]').after(html);
        });
</script>