<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpZipCodeValidator
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$allRegions = $block->getAllRegions();
$validationOptions = $block->getData("zipcodevalidationOptionsonEdit");
$product_id = $block->getRequest()->getParam('id');
if ($product_id) {
    $product = $block->getProduct($product_id);
    $type = $product->getTypeId();
    $visibility = $product->getVisibility();
    $selectedRegions = $product->getAvailableRegion();
    $selected = explode(',', $selectedRegions);
    $validationSelected = $product->getZipCodeValidation();
    
}
if ($type != 'virtual' && $type != 'downloadable' && $visibility != 1) {
    ?>
<div class="wk-zcv-valid-field" id="wk-zcv-valid-action-field">
    <div>
        <label class="wk-zcv-label">
            <?= $block->escapeHtml(__("Shipping Availability")); ?>:
        </label>
    </div>
    <div id="wk-zcv-option-field">
        <select name="product[zip_code_validation]" id="wk-zcv-valid-action">
            <?php foreach ($validationOptions as $key => $value) {?>
            <option value="<?= $block->escapeHtml($key); ?>" 
                <?php if ($validationSelected == 1) { echo "";
                } else { echo "selected"; } ?>
            >
                <?= $block->escapeHtml($value); ?>
            </option>
            <?php } ?>
        </select>
    </div>
</div>
<div class="field" id="wk-zcv-region-field">
    <div><label class="wk-zcv-label"><?= $block->escapeHtml(__("Available Regions")); ?>:</label></div>
    <div>
        <select multiple class="wk-zcv-multiple-select" name="product[available_region][]" required>
            <?php if (count($allRegions)) {
                foreach ($allRegions as $key => $value) { ?>
                <option value="<?= $block->escapeHtml($value->getId()); ?>" 
                    <?php if (in_array($value->getId(), $selected) && $validationSelected == 0) { echo "selected";
                    } elseif ($validationSelected == 3) {echo "selected";
                    } elseif ($validationSelected == 2 && in_array($value->getId(), $selected)) {echo "selected"; } ?> 
                >
                    <?= $block->escapeHtml($value->getRegionName()); ?>
                </option>
                <?php }
            } else { ?>
                <option value="0"><?= $block->escapeHtml(__("No Region Available")) ?></option>
            <?php } ?>
        </select>
    </div>
</div>

<script type="text/x-magento-init">
{
    "body": {
    "Webkul_MpZipCodeValidator/js/createproduct": {}
    }
}
</script>
<?php } ?>